//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleVerseDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleVerse
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string VerseGroup { get; set; }
        public string Book { get; set; }
        public Nullable<int> Chapter { get; set; }
        public Nullable<int> Verse { get; set; }
        public Nullable<int> ToVerse { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
        public string Language { get; set; }
        public string Translation { get; set; }
    }
}
