
DROP TABLE [dbo].[AppliedCashReceipts]
DROP TABLE [dbo].[CashReceipts]
DROP TABLE [dbo].CommissionsActual
DROP TABLE [dbo].[CommissionsRaw]
DROP TABLE [dbo].[CommissionsScheduled]
DROP TABLE [dbo].[DealerCustomerBalances]
DROP TABLE [dbo].[hostedmatchedmrcbackuplla614]
DROP TABLE [dbo].[importCHPriceList]
DROP TABLE [dbo].[ImportDealerCosts]
DROP TABLE [dbo].[importDealerQuoteUsocs]
--select 'DROP TABLE [dbo].' + name from sys.tables where name like 'lla%'
DROP TABLE [dbo].LLAImportMasterUSOCMatchInactive
DROP TABLE [dbo].LLAImportQBCashLog2011
DROP TABLE [dbo].LLAImportQBCashLog2012
DROP TABLE [dbo].[LLAImportUSOCNetworkInventory3-2013]
DROP TABLE [dbo].LLAImportCHSUSOCWholesaleFinal
DROP TABLE [dbo].LLAImportCHSUSOCRetailFinal
DROP TABLE [dbo].LLAImportUSOCNetworkInventoryV2
DROP TABLE [dbo].LLATempTAX201807
DROP TABLE [dbo].LLAtempLedge201807Edited
DROP TABLE [dbo].LLAtempLedger201807EditedNoComma
DROP TABLE [dbo].LLAMasterProductListBackup02072015
DROP TABLE [dbo].[LLAtempLedger-201807raw]
DROP TABLE [dbo].LLAImportSaddlebackLedgerMonthlyTotalBill
DROP TABLE [dbo].LLAImportInvoiceAuditExceptionList
DROP TABLE [dbo].LLAImportSaddlebackLedger201305
DROP TABLE [dbo].LLATMPVermeerTollBackup
DROP TABLE [dbo].LLATmpOSIOBTNs
DROP TABLE [dbo].LLARedRockMRCRetail
DROP TABLE [dbo].LLATmpOSIOBTNs2
DROP TABLE [dbo].LLARedRockMRCWholesale
DROP TABLE [dbo].LLARedRockOCCRetail
DROP TABLE [dbo].LLARedRockOCCWholesale
DROP TABLE [dbo].[LLAImportSaddlebackCashPosting4-19-2013]
DROP TABLE [dbo].LLARedRockTax
DROP TABLE [dbo].LLAImportSaddlebackTotalMonthlyBill402013
DROP TABLE [dbo].LLAredRockTollRetail
DROP TABLE [dbo].LLARedRockLedger
DROP TABLE [dbo].LLAImportUSOCRetail4192013
DROP TABLE [dbo].LLANetworkInventoryBackup08222015
DROP TABLE [dbo].LLAImportUSOCWholesale4192013
DROP TABLE [dbo].LLAImportMasterCustomerList
DROP TABLE [dbo].LLATempInvoiceSummary082017
DROP TABLE [dbo].LLAIMPORTRITUSOCs
DROP TABLE [dbo].[LLAImportSaddlebackOpenBalance4-19-2013]
DROP TABLE [dbo].LLAImportUSOCPriceList
DROP TABLE [dbo].LLAImportCHSCashPosting
DROP TABLE [dbo].LLAImportCHSMonthlyBilling
DROP TABLE [dbo].LLAImportCHSMonthlyBills
DROP TABLE [dbo].LLAImportSaddlebackCashPosting04252013
DROP TABLE [dbo].LLAImportLedger04262013
DROP TABLE [dbo].LLAPaymentsTemp
DROP TABLE [dbo].[NetworkInventory_bkp]
DROP TABLE [dbo].[Opportunities]
DROP TABLE [dbo].[numbers]
DROP TABLE [dbo].[OpportunityLineItems]
DROP TABLE [dbo].[OrderDetail]
DROP TABLE [dbo].[OrderFollowUps]
DROP TABLE [dbo].[Orders]
DROP TABLE [dbo].[screendefinitionbkp]
DROP TABLE [dbo].[TelaxCityDetailImortSample]
DROP TABLE [dbo].[tempNetworkInventoryUpdate]
DROP TABLE [dbo].[tmpCHSLocationsImport]
DROP TABLE [dbo].[tmpCommissionPaymentDates]
DROP TABLE [dbo].[tmpJCNetworkInventoryImport8-20-2015]
DROP TABLE [dbo].[tmpJM]
DROP TABLE [dbo].[tmpJM2]
DROP TABLE [dbo].[tmpJMscreenDefinition]
DROP TABLE [dbo].[tmpLLATAX201807]
DROP TABLE [import].[attributecustomerbackup]
DROP TABLE [import].[CustomerMasterList]


